---
apiVersion: packaging.carvel.dev/v1alpha1
kind: PackageInstall
metadata:
  name: app
  annotations:
    packaging.carvel.dev/downgradable: ""
spec:
  serviceAccountName: default
  packageRef:
    refName: rollback-sample.my-apps.vmware.com
    versionSelection:
      constraints: ">=0.0.0"
      #! constraints: 20230930014902.0.0+build.f943f02
  values:
  - secretRef:
      name: app-values