apiVersion: data.packaging.carvel.dev/v1alpha1
kind: Package
metadata:
  name: rollback-sample.my-apps.vmware.com.20230930014728.0.0+build.f943f02
spec:
  refName: rollback-sample.my-apps.vmware.com
  version: 20230930014728.0.0+build.f943f02
  releaseNotes: |
    Release v20230930014728.0.0+build.f943f02 of package rollback-sample.my-apps.vmware.com
  template:
    spec:
      fetch:
      - imgpkgBundle:
          image: shepherd2e6ad85996b27baa71a96f9a.azurecr.io/tap-install/workloads/rollback-sample-my-apps-bundle@sha256:752094244aef719daacea683ce51a43bd8f28778b614736940304ed638e75d89
      template:
      - ytt:
          paths:
          - .
      - kbld:
          paths:
          - .imgpkg/images.yml
          - '-'
      deploy:
      - kapp: {}
  valuesSchema:
    openAPIv3:
      type: object
      additionalProperties: false
      properties:
        workload_name:
          title: Workload name
          type: string
          description: Required. Name of the workload, used by K8s Ingress HTTP rules.
          default: ""
        replicas:
          title: Replicas
          type: integer
          description: Number of replicas.
          default: 1
        port:
          title: Port
          type: integer
          description: Port number for the backend associated with K8s Ingress.
          default: 8080
        hostname:
          title: Hostname
          type: string
          description: If set, K8s Ingress will be created with HTTP rules for hostname.
          default: ""
        cluster_issuer:
          title: Cluster Issuer
          type: string
          description: CertManager Issuer to use to generate certificate for K8s Ingress.
          default: tap-ingress-selfsigned

